# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/lynlab/luppiter-serverless-daemon
    steps:
      - checkout

      - run: go mod download
      - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run:
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)
